videoeditor/urls.py
from django.contrib import admin
from django.urls import path
from process.views import home, choose_file, video_url, progress, download, download_page
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('file/', choose_file, name='choose_file'),
    path('url/', video_url, name='video_url'),
    path('progress/<path:url>&fr=<int:fr>&fq=<int:fq>&fm=<int:fm>&ps=<ps>&ss=<int:ss>&st=<st>&qlty=<qlty>/',
         progress, name='progress'),
    path('download_page/', download_page, name='download_page'),
    path('download/', download, name='download')
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

process/forms.py
from django import forms
import numpy as np
import re

VALUES = [
    ('48000', '48000'),
    ('41000', '41000'),
    ]

PLAYBACK = np.arange(0.5, 3, 0.5)
PLAYBACK = zip(PLAYBACK.tolist(), PLAYBACK.tolist())


class InputParm(forms.Form):
    frame_rate = forms.IntegerField(widget=forms.Select(choices=VALUES), initial=48000)
    frame_quality = forms.IntegerField(initial=3)
    frame_margin = forms.IntegerField(initial=5)
    playback_speed = forms.FloatField(widget=forms.Select(choices=PLAYBACK), initial=1)
    silent_speed = forms.IntegerField(initial=100)
    silence_threshold = forms.FloatField(initial=0.03)

    def __init__(self, *args, **kwargs):
        super(InputParm, self).__init__(*args, **kwargs)  # Call to ModelForm constructor
        self.fields['frame_quality'].widget.attrs['min'] = 1
        self.fields['frame_margin'].widget.attrs['min'] = 0
        self.fields['silent_speed'].widget.attrs['min'] = 1
        self.fields['silence_threshold'].widget.attrs['min'] = 0

    def clean_frame_quality(self):
        frame_quality = self.cleaned_data['frame_quality']
        if 1 <= frame_quality <= 31:
            return frame_quality
        else:
            raise forms.ValidationError('Frame Quality Value must be in this range (1 to 31)')

    def clean_frame_margin(self):
        frame_margin = self.cleaned_data['frame_margin']
        if 0 <= frame_margin <= 120:
            return frame_margin
        else:
            raise forms.ValidationError('Frame Margin Value must be in this range (0 to 120)')

    def clean_playback_speed(self):
        playback_speed = self.cleaned_data['playback_speed']
        if 0.5 <= playback_speed <= 2.25:
            return playback_speed
        else:
            raise forms.ValidationError('Playback Speed Value must be in this range (0.5 to 2.25)')

    def clean_silent_speed(self):
        silent_speed = self.cleaned_data['silent_speed']
        if 1 <= silent_speed <= 100:
            return silent_speed
        else:
            raise forms.ValidationError('Silent Speed Value must be in this range (1 to 100)')

    def clean_silence_threshold(self):
        silence_threshold = self.cleaned_data['silence_threshold']
        if 0 <= silence_threshold <= 1:
            return silence_threshold
        else:
            raise forms.ValidationError('Silence Threshold Value must be in this range (0 to 1)')


QUALITY = [
    ('Default', 'Default'),
    ('1080p', '1080p'),
    ('720p', '720p'),
    ('480p', '480p'),
    ('360p', '360p'),
    ('240p', '240p'),
    ('144p', '144p')
]


class UrlForm(forms.Form):
    paste_URL = forms.URLField(widget=forms.TextInput(attrs={'rows': 1, 'cols': 100}), required=True)
    quality = forms.CharField(widget=forms.Select(choices=QUALITY), initial="Default")

    def clean_paste_URL(self):
        pattern = re.compile(r'.+youtube\.com/watch\?.+')
        paste_url = self.cleaned_data['paste_URL']
        if pattern.match(paste_url):
            print(paste_url)
            return paste_url
        else:
            raise forms.ValidationError('Please enter a youtube video')


def validate_file_extension(value):
    import os
    from django.core.exceptions import ValidationError
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.mp4', '.mov', '.mpeg', '.wmv']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Unsupported file extension.')


class UploadVideoForm(forms.Form):
    title = forms.CharField(max_length=70, required=True, initial="VideoShortCuts")
    file = forms.FileField(required=True, validators=[validate_file_extension])


class SubmitForm(forms.Form):
    origin_video_size = forms.CharField(required=False)
    origin_video_length = forms.CharField(required=False)
    new_video_size = forms.CharField(required=False)
    new_video_length = forms.CharField(required=False)

process/views.py
from .forms import InputParm, UrlForm, SubmitForm, UploadVideoForm
from django.urls import reverse
from django.shortcuts import render, HttpResponseRedirect
import os
from django.conf import settings
from django.http import HttpResponse, Http404
import re
from .consumers import YSTAMP


# Create your views here.
def home(request):
    template = 'process/home.html'
    context = {}
    return render(request, template, context)


def choose_file(request):
    if request.method == 'POST':
        video_form = UploadVideoForm(request.POST, request.FILES)
        form = InputParm(request.POST)
        if form.is_valid() and video_form.is_valid():
            cd = form.cleaned_data
            cd2 = video_form.cleaned_data
            ext = os.path.splitext(str(request.FILES['file']))[1]
            with open('static/media/video_input/{}{}'.format(cd2['title'], ext), 'wb+') as destination:
                for chunk in request.FILES['file'].chunks():
                    destination.write(chunk)
            return HttpResponseRedirect(reverse("progress", kwargs={'url': " ",
                                                                    'fr': cd['frame_rate'],
                                                                    'fq': cd['frame_quality'],
                                                                    'fm': cd['frame_margin'],
                                                                    'ps': cd['playback_speed'],
                                                                    'ss': cd['silent_speed'],
                                                                    'st': cd['silence_threshold'],
                                                                    'qlty': "Default"}))
        else:
            template = 'process/choose_file.html'
            context = {'form': form, 'video_form': video_form}
            return render(request, template, context)
    else:
        form = InputParm()
        video_form = UploadVideoForm()
        template = 'process/choose_file.html'
        context = {'form': form, 'video_form': video_form}
        return render(request, template, context)


def video_url(request):
    if request.method == 'POST':
        form = InputParm(request.POST)
        url_form = UrlForm(request.POST)
        if form.is_valid() and url_form.is_valid():
            cd = form.cleaned_data
            cd2 = url_form.cleaned_data
            return HttpResponseRedirect(reverse("progress", kwargs={'url': cd2['paste_URL'],
                                                                      'fr': cd['frame_rate'],
                                                                      'fq': cd['frame_quality'],
                                                                      'fm': cd['frame_margin'],
                                                                      'ps': cd['playback_speed'],
                                                                      'ss': cd['silent_speed'],
                                                                      'st': cd['silence_threshold'], 'qlty': cd2['quality']}))
        else:
            template = 'process/video_url.html'
            context = {'form': form, 'url_form': url_form}
            return render(request, template, context)
    else:
        form = InputParm()
        url_form = UrlForm()
        template = 'process/video_url.html'
        context = {'form': form, 'url_form': url_form}
        return render(request, template, context)


def progress(request, url, fr, fq, fm, ps, ss, st, qlty):
    template = "process/progress.html"
    submit_form = SubmitForm()
    context = {'submit_form': submit_form}
    return render(request, template, context)


def download(request):
    dir = os.path.join(settings.MEDIA_ROOT, "process\\{}".format(YSTAMP))
    pattern = re.compile(r'[-.\\/\s\w]+_videocuts_[-.\\/\s\w]+')
    for file in os.listdir(dir):
        if pattern.match(str(file)):
            path = "process\\{}\\".format(YSTAMP) + file
            file_path = os.path.join(settings.MEDIA_ROOT, path)
            if os.path.exists(file_path):
                with open(file_path, 'rb') as fh:
                    response = HttpResponse(fh.read(), content_type="video/mp4")
                    response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
                    return response
            raise Http404


def download_page(request):
    dir = os.path.join(settings.MEDIA_ROOT, "process\\{}".format(YSTAMP))
    pattern = re.compile(r'[-.\\/\s\w]+_videocuts_[-.\\/\s\w]+')
    for file in os.listdir(dir):
        if pattern.match(str(file)):
            path = "process\\{}\\".format(YSTAMP) + file
            file_path = os.path.join(settings.MEDIA_ROOT, path)
            if os.path.exists(file_path):
                template = 'process/download.html'
                context = {}
                return render(request, template, context)
            raise Http404

process/templates/process/base.html
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Document Title=============================================-->
    <title>VideoShortCuts</title>
    <!--Stylesheets=============================================-->
    <!-- Default stylesheets-->
    <link href="{% static 'lib/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Template specific stylesheets-->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Volkhov:400i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <link href="{% static 'lib/animate.css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'lib/components-font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/et-line-font/et-line-font.css' %}" rel="stylesheet">
    <link href="{% static 'lib/magnific-popup/dist/magnific-popup.css' %}" rel="stylesheet">
    <link href="{% static 'lib/simple-text-rotator/simpletextrotator.css' %}" rel="stylesheet">
    <!-- Main stylesheet and color file-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/local.css' %}" />
    <link id="color-scheme" href="{% static 'css/colors/default.css' %}" rel="stylesheet">
    <!-- Custom Style -->
    <style>
      .panel-heading {
          background-color: #023A38 !important;
          border-color: #023A38 !important;
          border-top: #023A38 !important;
      }

      .panel {
          border-top: #023A38 !important;
      }

      .dropdown>.dropdown-menu {
        transition: 1s all ease-in-out;
      }

      .btn-group>.dropdown>.dropdown-menu>li>a:hover {
          background-color: #606060 !important;
      }

      .btn-group>.dropdown>.dropdown-menu {
        top: 200%;
        transition: 0.7s all ease-in-out;
      }

      .btn-group>.dropdown:hover>.dropdown-menu {
        display: block;
        top: 100%;
        font-family: 'Volkhov' !important;
        font-style: normal !important;
        font-weight: 400 !important;
        background-color: #404040 !important;
      }

      .btn-group>.dropdown>.dropdown-toggle:active {
        /*Without this, clicking will make it sticky*/
          pointer-events: none;
      }

      {% block style %}
      {% endblock style %}
    </style>
  </head>
  <body data-spy="scroll" data-target=".onpage-navigation" data-offset="60">
    <main>
      <div id="wrapper">
         <nav class="navbar navbar-inverse navbar-custom navbar-fixed-top" role="navigation">
           <div class="container">
              <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#custom-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">VideoShortCuts</a>
              </div>
              <div class="collapse navbar-collapse navbar-ex1-collapse" id="custom-collapse">
                <ul id="active" class="nav navbar-nav side-nav">
                  <li><a href="#"><i class="fa fa-tachometer"></i> Dashboard</a></li>
                  <li><a href="{% url 'home' %}"><i class="fa fa-tachometer"></i> Home</a></li>
                  <li><a href="#"><i class="fa fa-sign-in" aria-hidden="true"></i> Sign In</a></li>
                  <li><a href="#"><i class="fa fa-list-ol"></i> Register</a></li>
                  <li><a href="#"><i class="fa fa-sign-out"></i> Sign Out</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown">File</a>
                  <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Check for updates</a></li>
                      <li><a href="https://michaelgrace.net/videocuts-downloads" target="_blank">Go to Downloads page</a></li>
                      <li><a href="https://michaelgrace.net/videocuts-downloads" target="_blank">License Agreement</a></li>
                      <li><a href="https://michaelgrace.net/videocuts-downloads" target="_blank">Register Software</a></li>
                      <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown">Tools</a>
                          <ul class="dropdown-menu">
                              <li><a href="https://michaelgrace.net/videcutsshareonfacebook" target="_blank">Open Transcriber</a></li>
                              <li><a href="https://michaelgrace.net/videocutsdownload" target="_blank">Download Video</a></li>
                          </ul>
                      </li>
                  </ul>
                  </li>
                  <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown">Options</a>
                  <ul class="dropdown-menu" role="menu">
                      <li><a href="https://michaelgrace.net/videocutsdownload" target="_blank">Save Settings</a></li>
                      <li><a href="https://michaelgrace.net/videocutsdownload" target="_blank">Load Settings</a></li>
                      <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown">Presets</a>
                      <ul class="dropdown-menu">
                          <li><a href="https://michaelgrace.net/videcutsshareonfacebook" target="_blank">Cut Silence</a></li>
                          <li><a href="https://michaelgrace.net/videocutsshareontwitter" target="_blank">Create Animation</a></li>
                          <li><a href="https://michaelgrace.net/linkedin" target="_blank">Shorten Lecture</a></li>
                      </ul>
                      </li>
                  </ul>
                  </li>
                  <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown">Help</a>
                  <ul class="dropdown-menu">
                    <li><a href="https://michaelgrace.net/videocuts-downloads">VideoShorts Home Page</a></li>
                    <li><a href="https://michaelgrace.net/videocuts-downloads">VideoShorts Tutorials</a></li>
                    <li><a href="https://michaelgrace.net/videocuts-downloads">Sign Up to Newsletter</a></li>
                    <li><a href="https://michaelgrace.net/videcutsshareonfacebook" target="_blank">Email us</a></li>
                    <li><a href="https://michaelgrace.net/videocuts-downloads" target="_blank">Share VideoShorts</a></li>
                    <li><a class="add-icon" href="https://michaelgrace.net/videocuts-downloads" target="_blank">Like VideoShorts on Facebook</a></li>
                    <li><a class="add-icon" href="https://michaelgrace.net/videocuts-downloads" target="_blank">Follow VideoShorts on Twitter</a></li>
                    <li><a href="https://michaelgrace.net/videocuts-downloads" target="_blank">Send Feedback or Suggestion</a></li>
                    <li><a href="https://michaelgrace.net/videocuts-downloads" target="_blank">Report a Bug</a></li>
                    <li><a href="https://michaelgrace.net/videcutsshareonfacebook" target="_blank">See Recommended Hardware</a></li>
                    <li><a href="https://michaelgrace.net/videocuts-downloads" target="_blank">Check for News</a></li>
                    <li><a href="https://michaelgrace.net/videocuts-downloads" target="_blank">Make Donation</a></li>
                    <li><a href="https://michaelgrace.net/videocuts-downloads" target="_blank">About VideoShorts</a></li>
                  </ul>
                  </li>
                </ul>
              </div>
           </div>
        </nav>
        <div id="page-wrapper">
          {% block select_video %}
          {% endblock select_video %}
        </div>
      </div>
    </main>
    <!--JavaScripts=============================================-->
    <!-- For redundancy===========================================-->
    <script src="{% static 'lib/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'lib/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <script src="{% static 'lib/wow/dist/wow.js' %}"></script>
    <script src="{% static 'lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js' %}"></script>
    <script src="{% static 'lib/smoothscroll.js' %}"></script>
    <script src="{% static 'lib/magnific-popup/dist/jquery.magnific-popup.js' %}"></script>
    <script src="{% static 'lib/simple-text-rotator/jquery.simple-text-rotator.min.js' %}"></script>
    <script src="{% static 'lib/imagesloaded/imagesloaded.pkgd.js' %}"></script>
    <script src="{% static 'lib/isotope/dist/isotope.pkgd.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript">
      {% block script %}
      {% endblock script %}
    </script>
  </body>
</html>

process/templates/process/choose_file.html
{% extends 'process/base.html' %}

{% block style %}
.errorlist
  {
      color: red;
  }

.panel .row
{
    padding-top: 10px;
    padding-bottom: 10px;
}

.row
{
    padding-top: 20px;
}

.row #panel-2
{
    margin-top: 40px !important;
}

input
{
    color: black;
}

select {
    color: black;
}

.form-2
{
    padding-top: 10px;
    padding-bottom: 10px;
}

.form-1, .form-2
{
    padding-left: 20px;
}

#reset {
    margin-left: 35px;
}

#id_file
{
    color: #66ff00;
}

{% endblock style %}

{% block select_video %}
<div class="row">
  <div class="col-lg-12">
    <form action="{% url 'choose_file' %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <div class="panel panel-default" id="panel-1">
      <div class="panel-heading"><h3 class="panel-title"><label>Select a Video</label></h3></div>
      <div class="row">
        <div class="panel-body">
            <div class="form-group field-wrapper form-1">
              <div class="col-md-8">
                {{ video_form.file.label_tag }} {{ video_form.file }}
                {{ video_form.file.errors }}
              </div>
              <div class="col-md-4">
                {{ video_form.title.label_tag }} {{ video_form.title }}
                {{ video_form.title.errors }}
              </div>
            </div>
        </div>
      </div>
    </div>
    <div class="panel panel-default" id="panel-2">
      <div class="panel-heading"><h3 class="panel-title"><label>Input Options</label></h3></div>
      {% if form.errors %}
        <p style="color: red;">
          please correct the error{{ form.errors|pluralize }}
        </p>
      {% endif %}
      <div class="row">
        <div class="col-sm-6">
        {% for field in form %}
          <div class="form-group field-wrapper form-2">
              {{ field.label_tag }} {{ field }}
              {{ field.errors }}
          </div>
          {% cycle "" "" "</div><div class='col-sm-6'>" %}
        {% endfor %}
        </div>
        <button onclick="dialog()" id="submit" type="submit" class="btn btn-default" value="Submit">Submit</button>
        <button onclick="reset()" id="reset" type="reset" class="btn btn-default">Reset</button>
      </div>
    </div>
   </form>
  </div>
</div>
{% endblock select_video %}

{% block script %}
const stateObj = { home: 'home' }
window.history.pushState(stateObj, null, "{% url 'home' %}")
window.onpopstate = function(event) {
  alert("You will be taken back to the home page")
}
{% endblock script %}

process/templates/process/download.html
{% extends 'process/base.html' %}
{% load static %}

{% block style %}
.panel .row
{
    padding-top: 10px;
    padding-bottom: 10px;
    padding-left: 30px;
}

.panel .row .col-sm-6
{
    padding-top: 5px;
    padding-bottom: 5px;
    padding-left: 30px;
}

.row
{
    padding-top: 20px;
}

.row #panel-1
{
    margin-top: 10px !important;
}

.row #panel-2
{
    margin-top: 40px !important;
}

.form-1
{
    padding-left: 20px;
}

#view
{
  margin-top: 25px !important;
}

{% endblock style %}

{% block select_video %}
<div class="row">
  <div class="col-lg-12">
      <div class="panel panel-default" id="panel-1">
        <div class="panel-heading"><h3 class="panel-title"><label id="head">Download or View Edited Video</label></h3></div>
          <div class="row">
            <div class="panel-body">
              <div class="form-group field-wrapper form-1">
                <div class="row">
                <div class="col-md-6">
                <p>Download the edited video</p>
                </div>
                <div class="col-md-6">
                  <p>View video in browser</p>
                </div>
                </div>
              <div class="row">
                <div class="col-md-6">
                <a href="{% url 'download' %}" download>
                  <img src="{% static 'img/download_icon.png' %}" width="150" height="142">
                </a>
                </div>
                <div class="col-md-6" id="sec">
                <a href="{% url 'download' %}" target="_blank">
                  <img src="{% static 'img/video_icon.png' %}" width="100" height="142" id="view">
                </a>
                </div>
                </div>
              </div>
            </div>
          </div>
      </div>
  </div>
</div>
{% endblock select_video %}

{% block script %}
const stateObj = { home: 'home' }
window.history.pushState(stateObj, null, "{% url 'home' %}")
window.onpopstate = function(event) {
  alert("You will be taken back to the home page")
}
{% endblock script %}

process/templates/process/home.html
{% extends 'process/base.html' %}


{% block style %}
.btn-group > .dropdown > button {
  width: 25em !important;
}

.btn-group>.dropdown:hover>.dropdown-menu {
  width: 25em !important;
}

.panel {
  margin-top: 20px;
}
{% endblock style %}

{% block select_video %}
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading"><h3 class="panel-title"><label>Select a Video</label></h3></div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-10 text-center">
            <div class="btn-group">
              <div class="dropdown">
                <button type="button" class="btn btn-default dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span>Video Source</span>
                <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-center text-center" aria-labelledby="dropdownMenuButton">
                  <li><a class="dropdown-item" href="{% url 'choose_file' %}">Choose File</a></li>
                  <li><a class="dropdown-item" href="{% url 'video_url' %}">Video URL</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock select_video %}

{% block script %}
const stateObj = { home: 'home' }
window.history.pushState(stateObj, null, "{% url 'home' %}")
{% endblock script %}

process/templates/process/video_url.html
{% extends 'process/base.html' %}

{% block style %}
.errorlist
  {
      color: red;
  }

.panel .row
{
    padding-top: 10px;
    padding-bottom: 10px;
}

.panel .row .col-sm-6
{
    padding-top: 5px;
    padding-bottom: 5px;
}

.row
{
    padding-top: 20px;
}

.row #panel-2
{
    margin-top: 40px !important;
}

#id_paste_URL
{
    width: 500px;
    margin-left: 15px;
}

.form-1, .form-2
{
    padding-left: 20px;
}

.form-2
{
    padding-top: 10px;
    padding-bottom: 10px;
}

.btn
{
    margin-bottom: 8px;
}

input
{
    color: black;
}

select {
    color: black;
}

#reset {
    margin-left: 35px;
}

{% endblock style %}

{% block select_video %}
<div class="row">
  <div class="col-lg-12">
    <form class="form" action="{% url 'video_url' %}" method="post">
      {% csrf_token %}
      <div class="panel panel-default" id="panel-1">
        <div class="panel-heading"><h3 class="panel-title"><label>Enter a Youtube Video URL</label></h3></div>
          <div class="row">
            <div class="panel-body">
              <div class="form-group field-wrapper form-1">
                <div class="col-md-8">
                  {{ url_form.paste_URL.label_tag }} {{ url_form.paste_URL }}
                  {{ url_form.paste_URL.errors }}
                </div>
                <div class="col-md-4">
                  {{ url_form.quality.label_tag }} {{ url_form.quality }}
                  {{ url_form.quality.errors }}
                </div>
              </div>
            </div>
          </div>
      </div>
      <div class="panel panel-default" id="panel-2">
        <div class="panel-heading"><h3 class="panel-title"><label>Input Options</label></h3></div>
        {% if form.errors %}
          <p style="color: red;">
            please correct the error{{ form.errors|pluralize }}
          </p>
        {% endif %}
        <div class="row">
          <div class="col-sm-6">
          {% for field in form %}
            <div class="form-group field-wrapper form-2">
                {{ field.label_tag }} {{ field }}
                {{ field.errors }}
            </div>
            {% cycle "" "" "</div><div class='col-sm-6'>" %}
          {% endfor %}
          </div>
          <button onclick="dialog()" id="submit" type="submit" class="btn btn-default" value="Submit">Submit</button>
          <button onclick="reset()" id="reset" class="btn btn-default">Reset</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock select_video %}

{% block script %}
const stateObj = { home: 'home' }
window.history.pushState(stateObj, null, "{% url 'home' %}")
window.onpopstate = function(event) {
  alert("You will be taken back to the home page")
}
{% endblock script %}